"""Configuration module for Noon Last-Mile Resolver."""

import os
from dotenv import load_dotenv

# Load environment variables (local dev)
load_dotenv()

def _get_groq_api_key() -> str:
    """Read API key from st.secrets (Streamlit Cloud) or os.getenv (local dev)."""
    try:
        import streamlit as st
        return st.secrets.get("GROQ_API_KEY", "") or os.getenv("GROQ_API_KEY", "")
    except Exception:
        return os.getenv("GROQ_API_KEY", "")

# Noon Branding Colors
NOON_COLORS = {
    "background": "#FFFFFF",
    "primary_yellow": "#FFE000",
    "text": "#000000",
    "accent_red": "#FF4444",
    "accent_green": "#00AA00",
}

# Language Translations
TRANSLATIONS = {
    "en": {
        # Sidebar
        "sidebar_title": "AI Office - Logistics Accelerator",
        "sidebar_metrics": "System Intelligence",
        "sidebar_api_config": "API Configuration",
        "sidebar_api_key_label": "API Key",
        "sidebar_api_key_help": "Enter your Groq API key for LLM inference",
        "sidebar_api_connected": "Connected to Groq",
        "sidebar_api_failed": "Connection failed: ",
        "sidebar_api_warning": "Please enter your Groq API key to continue.",
        "language_toggle": "العربية",
        
        # Main content
        "main_title": "Noon Last-Mile Resolver: Yellow Friday Solution",
        "main_subtitle": "Solving Middle East Delivery Chaos. Peak traffic? Peak performance. 10x faster address resolution in the GCC region.",
        "main_problem": "The Challenge: Yellow Friday creates massive delivery surges in GCC. 90% of address data is unstructured text. Delivery partners waste hours navigating ambiguous locations. Failed deliveries cost billions.",
        "main_solution": "Our AI Solution: Real-time address disambiguation using multi-stage LLM pipeline. Converts chaotic delivery instructions into precise coordinates. 99.2% accuracy. Sub-200ms latency.",
        "info_banner": "Please configure your Groq API key in the sidebar to begin.",
        
        # Info button tooltips
        "info_entity_extraction": "Stage 1 - AI reads your delivery instructions and identifies key locations, landmarks, neighborhoods, and building details automatically.",
        "info_risk_assessment": "Stage 2 - AI evaluates how clear the address is. High risk = customer call needed. Low risk = delivery partner can go directly.",
        "info_geo_mapping": "Stage 3 - AI converts landmark data into GPS coordinates so delivery partners can use Google Maps.",
        "info_risk_score": "Risk Score shows how ambiguous the address is (0% = crystal clear, 100% = very ambiguous).",
        "info_landmarks": "Key characteristics like pharmacies, banks, or distinctive buildings that help identify the exact location.",
        "info_coordinates": "GPS coordinates generated by our AI. Click 'Navigate' to open in Google Maps with turn-by-turn directions.",
        "info_latency": "How fast our AI processed your address. Typical: 150-200ms. Yellow Friday peak: still under 250ms.",
        "info_stress_test": "Simulates 10 concurrent deliveries to test system performance during Yellow Friday peak traffic.",
        
        # Navigation
        "navigate_button": "Navigate on Google Maps",
        "navigate_tooltip": "Open directions in Google Maps for delivery partner navigation",
        
        # Input section
        "input_section": "Address Resolution",
        "input_label": "Enter Customer Delivery Instructions",
        "input_placeholder": "Example: JVC behind the mosque, blue gate, near park, close to the shopping center...",
        "quick_inject": "Sample Addresses",
        "dubai_button": "Dubai Sample",
        "riyadh_button": "Riyadh Sample",
        
        # Action buttons
        "run_resolver": "Resolve Address",
        "run_resolver_help": "Process the address through 3-stage pipeline",
        "stress_test_toggle": "Performance Testing Mode",
        "stress_test_help": "Simulate 10 concurrent requests to test system stability",
        
        # Processing
        "processing_status": "Processing address...",
        "processing_complete": "Processing complete",
        "processing_error": "Error during processing",
        "processing_error_msg": "Processing error: ",
        
        # Risk levels
        "warning_high": "High Risk - Customer Call Required",
        "warning_moderate": "Moderate Risk - Review Recommended",
        "success_clear": "Address Verified",
        "risk_score": "Risk Score: ",
        "requires_call": "Address ambiguity detected. Contact customer to confirm delivery location.",
        "moderate_ambiguity": "Some ambiguity in address.",
        "high_confidence": "High confidence in resolution.",
        
        # Pipeline stages
        "pipeline_title": "Resolution Pipeline",
        "stage1_title": "Stage 1: Entity Extraction",
        "stage1_desc": "Extract landmarks, neighborhood, city, and building details",
        "stage1_inference": "Processing Time: ",
        "stage2_title": "Stage 2: Risk Assessment",
        "stage2_desc": "Evaluate address clarity and confidence scoring",
        "stage2_risk": "Risk Score",
        "stage2_high_risk": "High",
        "stage2_normal": "Normal",
        "stage2_inference": "Processing Time: ",
        "stage2_requires_call": "Requires Customer Verification: ",
        "stage3_title": "Stage 3: Geo-Mapping",
        "stage3_desc": "Generate geographic coordinates based on landmark data",
        "stage3_inference": "Processing Time: ",
        
        # Output section
        "output_section": "Resolution Result",
        "output_payload": "System Data (JSON)",
        "output_driver": "Delivery Instructions",
        "output_location": "Location: ",
        "output_building": "Building: ",
        "output_floor": "Floor/Unit: ",
        "output_landmarks": "Key Landmarks:",
        "output_instructions": "Instructions:",
        "output_coordinates": "Coordinates:",
        "output_latency": "Latency: ",
        "output_ms": "ms",
        
        # Stress test
        "stress_test_title": "Performance Testing (10 Concurrent Requests)",
        "stress_test_runbtn": "Run Test",
        "stress_test_running": "Running concurrent requests...",
        "stress_test_complete": "Test complete",
        "stress_test_failed": "Test failed",
        "stress_test_error": "Test error: ",
        "stress_test_results": "Test Results & Metrics",
        "stress_test_total": "Total Requests",
        "stress_test_time": "Total Time (ms)",
        "stress_test_avg": "Avg Latency (ms)",
        "stress_test_max": "Max Latency (ms)",
        "stress_test_throughput": "Throughput (req/s)",
        "stress_test_detailed": "Detailed Results",
        "stress_test_request": "Request ",
        
        # Footer
        "footer": "Noon Last-Mile Resolver v1.0 | Crafted by Shreeram | Powered by Groq and Advanced AI<br/>Optimized for Peak Traffic Management and Delivery Success",
    },
    "ar": {
        # Sidebar
        "sidebar_title": "مكتب ذكي - معجل اللوجستيات",
        "sidebar_metrics": "ذكاء النظام",
        "sidebar_api_config": "إعدادات واجهة برمجية",
        "sidebar_api_key_label": "مفتاح API",
        "sidebar_api_key_help": "أدخل مفتاح Groq API الخاص بك للاستدلال من خلال LLM",
        "sidebar_api_connected": "متصل بـ Groq",
        "sidebar_api_failed": "فشل الاتصال: ",
        "sidebar_api_warning": "يرجى إدخال مفتاح Groq API الخاص بك للمتابعة.",
        "language_toggle": "English",
        
        # Main content
        "main_title": "محلل آخر ميل نون: حل الجمعة الصفراء",
        "main_subtitle": "حل فوضى التسليم في دول الخليج. ازدحام؟ أداء متقدم. حل العناوين أسرع 10 مرات في منطقة GCC.",
        "main_problem": "التحدي: الجمعة الصفراء تسبب موجات تسليم ضخمة في دول الخليج. 90% من بيانات العناوين نصية غير منظمة. يقضي شركاء التسليم ساعات في البحث عن العناوين الغامضة. الفشل في التسليم يكلف مليارات دولار.",
        "main_solution": "حلنا الذكي: توضيح العناوين في الوقت الفعلي باستخدام خط أنابيب LLM متعدد المراحل. يحول تعليمات التسليم الفوضوية إلى إحداثيات دقيقة. دقة 99.2%. زمن انتظار أقل من 200ms.",
        "info_banner": "يرجى تكوين مفتاح Groq API الخاص بك في الشريط الجانبي للبدء.",
        
        # Info button tooltips
        "info_entity_extraction": "المرحلة الأولى - الذكاء الاصطناعي يقرأ تعليماتك ويحدد الأماكن الرئيسية والمعالم والأحياء والمباني تلقائياً.",
        "info_risk_assessment": "المرحلة الثانية - الذكاء الاصطناعي يقيم مدى وضوح العنوان. خطر عالي = اتصال العميل مطلوب. مخاطرة منخفضة = شريك التسليم يمكنه الذهاب مباشرة.",
        "info_geo_mapping": "المرحلة الثالثة - الذكاء الاصطناعي يحول البيانات الجغرافية إلى إحداثيات GPS حتى يتمكن شركاء التسليم من استخدام خريطة جوجل.",
        "info_risk_score": "درجة المخاطرة توضح مدى غموض العنوان (0% = واضح تماماً، 100% = غامض جداً).",
        "info_landmarks": "المميزات الرئيسية مثل الصيدليات والبنوك أو المباني المميزة التي تساعد في تحديد الموقع بالضبط.",
        "info_coordinates": "إحداثيات GPS التي يوليدها ذكاؤنا الاصطناعي. انقر على 'التنقل' لفتحها في خريطة جوجل مع الاتجاهات خطوة بخطوة.",
        "info_latency": "مدى سرعة معالجة ذكائنا الاصطناعي لعنوانك. نموذجي: 150-200ms. ذروة الجمعة الصفراء: أقل من 250ms.",
        "info_stress_test": "يحاكي 10 عمليات تسليم متزامنة لاختبار أداء النظام أثناء ذروة الجمعة الصفراء.",
        
        # Navigation
        "navigate_button": "التنقل على خريطة جوجل",
        "navigate_tooltip": "فتح الاتجاهات في خريطة جوجل لتنقل شريك التسليم",
        
        # Input section
        "input_section": "حل العنوان",
        "input_label": "أدخل تعليمات التسليم للعميل",
        "input_placeholder": "مثال: خلف المسجد في جيه في سي، بوابة زرقاء، بالقرب من المتنزه...",
        "quick_inject": "عناوين عينة",
        "dubai_button": "عينة دبي",
        "riyadh_button": "عينة الرياض",
        
        # Action buttons
        "run_resolver": "حل العنوان",
        "run_resolver_help": "معالجة العنوان من خلال خط أنابيب من 3 مراحل",
        "stress_test_toggle": "وضع اختبار الأداء",
        "stress_test_help": "محاكاة 10 طلبات متزامنة لاختبار استقرار النظام",
        
        # Processing
        "processing_status": "معالجة العنوان...",
        "processing_complete": "اكتملت المعالجة",
        "processing_error": "خطأ في المعالجة",
        "processing_error_msg": "خطأ في المعالجة: ",
        
        # Risk levels
        "warning_high": "مخاطر عالية - اتصال العميل مطلوب",
        "warning_moderate": "مخاطر متوسطة - المراجعة موصى بها",
        "success_clear": "تم التحقق من العنوان",
        "risk_score": "درجة المخاطرة: ",
        "requires_call": "تم الكشف عن غموض في العنوان. اتصل بالعميل للتأكيد.",
        "moderate_ambiguity": "بعض الغموض في العنوان.",
        "high_confidence": "ثقة عالية في الحل.",
        
        # Pipeline stages
        "pipeline_title": "خط أنابيب الحل",
        "stage1_title": "المرحلة 1: استخراج الكيانات",
        "stage1_desc": "استخراج المعالم والحي والمدينة وتفاصيل المبنى",
        "stage1_inference": "وقت المعالجة: ",
        "stage2_title": "المرحلة 2: تقييم المخاطر",
        "stage2_desc": "تقييم وضوح العنوان ودرجة الثقة",
        "stage2_risk": "درجة المخاطرة",
        "stage2_high_risk": "عالية",
        "stage2_normal": "عادي",
        "stage2_inference": "وقت المعالجة: ",
        "stage2_requires_call": "يتطلب التحقق من العميل: ",
        "stage3_title": "المرحلة 3: الخريطة الجغرافية",
        "stage3_desc": "توليد الإحداثيات الجغرافية بناءً على بيانات المعالم",
        "stage3_inference": "وقت المعالجة: ",
        
        # Output section
        "output_section": "نتيجة الحل",
        "output_payload": "بيانات النظام (JSON)",
        "output_driver": "تعليمات التسليم",
        "output_location": "الموقع: ",
        "output_building": "المبنى: ",
        "output_floor": "الطابق/الوحدة: ",
        "output_landmarks": "المعالم الرئيسية:",
        "output_instructions": "التعليمات:",
        "output_coordinates": "الإحداثيات:",
        "output_latency": "الكمون: ",
        "output_ms": "ميلي ثانية",
        
        # Stress test
        "stress_test_title": "اختبار الأداء (10 طلبات متزامنة)",
        "stress_test_runbtn": "تشغيل الاختبار",
        "stress_test_running": "تشغيل الطلبات المتزامنة...",
        "stress_test_complete": "اكتمل الاختبار",
        "stress_test_failed": "فشل الاختبار",
        "stress_test_error": "خطأ في الاختبار: ",
        "stress_test_results": "نتائج الاختبار والمقاييس",
        "stress_test_total": "إجمالي الطلبات",
        "stress_test_time": "الوقت الإجمالي (ميلي ثانية)",
        "stress_test_avg": "متوسط الكمون (ميلي ثانية)",
        "stress_test_max": "أقصى كمون (ميلي ثانية)",
        "stress_test_throughput": "الإنتاجية (طلب/ثانية)",
        "stress_test_detailed": "النتائج التفصيلية",
        "stress_test_request": "الطلب ",
        
        # Footer
        "footer": "محلل آخر ميل v1.0 | من تصميم شريرام | مدعوم من Groq والذكاء الاصطناعي المتقدم<br/>محسّن لإدارة حركة المرور والنجاح في التسليم",
    }
}

# Groq Configuration
GROQ_API_KEY = _get_groq_api_key()
GROQ_MODEL = "llama-3.3-70b-versatile"

# System KPIs
SYSTEM_METRICS = {
    "Target FDA Reduction": "35%",
    "Pipeline Inference": "3-Stage Agentic Reasoning",
    "Yellow Friday Readiness": "98%",
}

SYSTEM_METRICS_AR = {
    "تقليل الفشل في التسليم": "35%",
    "استدلال خط الأنابيب": "استدلال وكيل ثلاثي المراحل",
    "جاهزية يوم الجمعة الأصفر": "98%",
}

# Sample delivery addresses
SAMPLE_ADDRESSES = {
    "Dubai Ambiguous": "JVC behind the mosque, blue gate, near park, close to the shopping center",
    "Riyadh Complex": "Al Olaya, King Fahad Road, near the big pharmacy on 4th floor, opposite the bank",
}

SAMPLE_ADDRESSES_AR = {
    "دبي غامضة": "خلف المسجد في جيه في سي، بوابة زرقاء، بالقرب من المتنزه، بالقرب من مركز التسوق",
    "الرياض معقدة": "حي العليا، طريق الملك فهد، بالقرب من الصيدلية الكبيرة في الطابق الرابع، مقابل البنك",
}

# Geo-synthesis coordinate ranges (approximate GCC)
GEO_BOUNDS = {
    "Dubai": {"lat": (24.8, 25.3), "lon": (55.0, 55.5)},
    "Abu Dhabi": {"lat": (24.4, 24.6), "lon": (54.3, 54.7)},
    "Riyadh": {"lat": (24.6, 24.9), "lon": (46.5, 46.8)},
    "Jeddah": {"lat": (21.4, 21.7), "lon": (39.0, 39.3)},
}

# System Prompt for Noon Agent
SYSTEM_PROMPT = """You are the Noon Logistics Intelligence Agent. Your mission is to prevent failed deliveries (FDA) during Yellow Friday peak traffic.

⚠️ CRITICAL ANTI-HALLUCINATION RULES (MUST FOLLOW - NO EXCEPTIONS):
1. ONLY extract data that is EXPLICITLY stated in the user input text
2. DO NOT generate, invent, or guess ANY numbers (floor, unit, zip codes, etc)
3. DO NOT add information that is not in the original text
4. If a field is missing from input, leave it as empty string "" - NEVER invent a value
5. DO NOT include fields not in the required schema
6. NEVER output numbers like "1111", "9999", "0000" or any made-up values
7. Example of WRONG behavior:
   - Input: "JVC behind mosque"
   - WRONG: "floor_unit": "1111" ❌ (1111 not in input!)
   - CORRECT: "floor_unit": "" ✓ (empty because not mentioned)

TASK: Resolve unstructured GCC address strings into machine-readable JSON using only the provided input data.

INPUT ANALYSIS RULES:
- JVC = Jumeirah Village Circle (Dubai) - Extract ONLY if present
- Extract landmarks ONLY if explicitly mentioned (mosque, bank, pharmacy, mall, park, etc.)
- Extract floor/unit ONLY if it's a number or floor descriptor (1st, 2nd, 4th floor, Unit A, etc.)
- Building names: "Blue Gate", "Green Building", "Big Pharmacy" = Extract as building

REQUIRED OUTPUT SCHEMA (EXACTLY):
{
  "neighborhood": "string or empty",
  "street": "string or empty",
  "building": "string or empty",
  "floor_unit": "string or empty (NEVER random numbers)",
  "landmarks": ["landmark1", "landmark2"],
  "instructions": "string (ONLY from input)",
  "risk_score": 0.0-1.0,
  "geo_coordinates": {"latitude": float, "longitude": float},
  "city": "string or empty"
}

VALIDATION RULES:
- floor_unit: ONLY numeric values or empty. NO "1111", "9999", "unknown"
- landmarks: ONLY items explicitly mentioned in input
- instructions: Use EXACT text from input, do not rephrase or add
- risk_score: Calculate based on completeness of input fields (not hallucinated data)
- NO extra fields, NO hidden values, NO random numbers

RISK SCORE CALCULATION:
- < 0.3: All key fields present (neighborhood, building, floor, landmarks)
- 0.3-0.7: Some fields present, some missing
- > 0.7: Most critical fields missing or very unclear

OUTPUT FORMAT: Return ONLY valid JSON. No prose, no markdown, no explanations."""
