[theme]
primaryColor = "#FFE000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = true
showWarningOnDirectExecution = false
toolbarMode = "auto"

[logger]
level = "info"

[server]
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false
